version: 1
name: "tt-rs Explainer Video"
description: >
  TBT #4: ToonTalk Visual Programming - tt-rs explainer video.
  Landscape 1920x1080, ~45 seconds total.
  Sections: title, hook, intro-demo, demo (placeholder), cta, epilog, epilog-ext.

vars:
  project_name: "tt-rs Explainer"
  topic: "ToonTalk Visual Programming"
  duration_secs: "45"
  style: "straightforward, professional"
  audience: "developers interested in visual programming"
  # TTS voice cloning settings
  python_path: "/Users/mike/github/softwarewrighter/video_workflow_rs/test-projects/tt-rs-explainer/.venv/bin/python"
  tts_server: "http://curiosity:7860"
  reference_audio: "/Users/mike/github/softwarewrighter/video-publishing/reference/voice/mike-medium-ref-1.wav"
  reference_text: "In this session, I'm going to write a small command line tool and explain the decision making process as I go. I'll begin with a basic skeleton, argument parsing, a configuration loader, and a minimal main function. Once everything compiles, I'll run it with a few sample inputs to confirm the behavior. After that, I'll be fine the internal design. I'll reorganize the functions, extract shared logic, and add error messages that actually help the user understand what went wrong. None of this is complicated, but it's the kind of work that separates a rough prototype from a tool someone can rely on. As we move forward, I'll highlight why I chose certain patterns, some decisions, optimize clarity, while others optimize performance or extensibility. The important thing is to understand the trade-offs well enough that the code feels intentional instead of accidental."

steps:
  # Setup directories
  - id: ensure_dirs
    kind: ensure_dirs
    dirs:
      - "work/scripts"
      - "work/audio"
      - "work/images"
      - "work/clips"
      - "output"

  # Write production manifest
  - id: write_manifest
    kind: write_file
    path: "output/manifest.txt"
    content: |
      tt-rs Explainer Video Production
      =================================
      Project: {{project_name}}
      Topic: {{topic}}
      Format: Landscape 1920x1080 (16:9)
      Duration: ~{{duration_secs}} seconds

      Structure:
      - 00-title (5s) - Robot video on white background with #TBT, tt-rs, ToonTalk text
      - 01-hook (~5s) - "What if you could teach a computer..."
      - 02-intro-demo (~5s) - "tt-rs is a modern Rust and WebAssembly..."
      - 03-demo (variable) - OBS screen capture placeholder
      - 04-cta (~5s) - "Try the live demo..."
      - 99a-epilog (~12s) - Standard epilog
      - 99b-epilog-ext (7s) - Epilog frame with music

      Assets:
      - assets/robot.mp4 - Robot video for title compositing
      - assets/epilog.mp4 - Standard epilog video
      - assets/epilog-frame.png - Last frame for epilog extension
      - assets/music-upbeat.wav - Background music (8s, seed 1234)

      Narration Scripts:
      - work/scripts/01-hook.txt
      - work/scripts/02-intro-demo.txt
      - work/scripts/03-cta.txt

      Generated Images:
      - work/images/title-background.png
      - work/images/demo-placeholder.png

      Build:
      - scripts/build-video.sh - Assembles preview video
      - output/preview.mp4 - Final preview output

      Next Steps:
      1. Record OBS demo clips
      2. Update build script with real audio/demo
      3. Rebuild: scripts/build-video.sh

  # TTS Audio Generation
  - id: tts_hook
    kind: tts_generate
    resume_output: "work/audio/01-hook.wav"
    script_path: "work/scripts/01-hook.txt"
    output_path: "work/audio/01-hook.wav"
    server: "{{tts_server}}"
    reference_audio: "{{reference_audio}}"
    reference_text: "{{reference_text}}"
    python_path: "{{python_path}}"

  - id: tts_intro_demo
    kind: tts_generate
    resume_output: "work/audio/02-intro-demo.wav"
    script_path: "work/scripts/02-intro-demo.txt"
    output_path: "work/audio/02-intro-demo.wav"
    server: "{{tts_server}}"
    reference_audio: "{{reference_audio}}"
    reference_text: "{{reference_text}}"
    python_path: "{{python_path}}"

  - id: tts_cta
    kind: tts_generate
    resume_output: "work/audio/03-cta.wav"
    script_path: "work/scripts/03-cta.txt"
    output_path: "work/audio/03-cta.wav"
    server: "{{tts_server}}"
    reference_audio: "{{reference_audio}}"
    reference_text: "{{reference_text}}"
    python_path: "{{python_path}}"

  # Build video preview
  - id: build_video
    kind: run_command
    program: "./scripts/build-video.sh"
    capture_path: "output/build.log"
